<!DOCTYPE html>
<html lang="en" xml:lang="en" manifest="BQ.manifest">
<head>
   <meta charset="utf-8">

   <title>Bible Quiz</title>
   <meta name="application-name" content="Bible Quiz">
   <meta name="Author" content="Jeff Falter">
   <meta name="Copyright" content="copyright 2013-2015 by Jeff Falter">
   <meta name="Description" content="Bible trivia quiz for fun and educational purposes">

   <!--  These tags are needed for mobile devices -->
   <meta name="mobile-web-app-capable" content="yes">
   <meta name="apple-mobile-web-app-capable" content="yes">
   <meta name="apple-mobile-web-app-status-bar-style" content="black">
   <meta name="apple-mobile-web-app-title" content="Bible Quiz">
   <link rel="address bar icon" href="images/BQ-32.png">
   <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">


   <!-- jQuery scripts -->
   <link rel="stylesheet" href="jquery/jquery.mobile-1.4.5.min.css">
   <script src="jquery/jquery-2.1.3.js"></script>
   <script src="jquery/jquery.mobile-1.4.5.min.js"></script>
	<!-- <script src="jquery/jquery.idb.source.js"></script> -->

   <!-- My style sheet -->
   <link rel="stylesheet" type="text/css" href="BQ.css">

   <!-- My script -->
   <script type="text/javascript" src="BQ.js"></script>

   <!-- Icons for the user's home screen -->
   <link rel="shortcut icon" sizes="196x196" href="images/BQ-196.png">
   <link rel="apple-touch-icon" sizes="128x128" href="images/BQ-128.png" />
   <meta name="msapplication-TileImage" content="images/BQ-300.png"/>

</head>

<body>

   <!-- ======================================================================================= -->

