
   <div data-role="page" id="BQ_Start">

      <div data-role="header" data-position="fixed" data-id="nav" id="BQ_Start_Title" data-theme="b">
         <h1 id="BQ_Start_app_name">Bible Quiz</h1>
      </div><!-- data-role: header, id: title -->

      <div id="BQ_Start_PageContent" data-role="content">
         <div class="centerAlign">
            <img id="BQ_Start_Logo" src="images/BQ-300.png" alt="Bible Quiz logo"/>
            <p>Ready to test your knowledge?</p>
            <a id="BQ_Start_NewGame" href="#BQ_Game" data-role="button" data-theme="a">Start</a>
         </div>
      </div><!-- data-role: content -->

      <div data-role="footer" data-position="fixed" data-id="nav" data-theme="b">
         <div data-role="navbar">
            <ul id="BQ_Start_secondary">
               <li><a id="BQ_Start_Config" href="#BQ_Config" data-icon="gear">Config</a></li>
               <li><a href="#BQ_Stats"  data-icon="bullets">Stats</a></li>
               <li><a href="#BQ_About"  data-icon="info">About</a></li>
               <!-- <li><a onclick="window.close()" data-icon="delete">Exit</a></li> -->
            </ul>
          </div><!-- data-role: navbar -->
      </div><!-- data-role: footer -->

   </div><!-- data-role: page, id: BQ_Start -->

   <!-- ======================================================================================= -->
