
   <div data-role="page" id="BQ_Game">

      <div data-role="header" data-position="fixed" data-id="nav" id="BQ_Game_Title" data-theme="b">
         <h1 id="BQ_Game_app_name">Bible Quiz | Play</h1>
      </div><!-- data-role: header, id: title -->

      <div id="BQ_Game_PageContent" data-role="content">

         <fieldset data-role="controlgroup">
         
	         <legend class="question">In the book of Deuteronomy, which statement follows "Hear, O Israel: The <span class='tetragrammaton'>Lord</span> is our God, the <span class='tetragrammaton'>Lord</span> alone."</legend>
	
	         <input type="radio" name="answer" id="answerA" value="A" data-theme="a" />
	         <label for="answerA">You shall have no other gods before me.</label>

	         <input type="radio" name="answer" id="answerB" value="B" data-theme="a" />
	         <label for="answerB">You shall love the <span class='tetragrammaton'>Lord</span> your God with all your heart, and with all your soul, and with all your might."</label>
	
            <input type="radio" name="answer" id="answerC" value="C" data-theme="a" />
	         <label for="answerC">You shall remember all the ways which the <span class='tetragrammaton'>Lord</span> your God has led you.</label>
	            
            <input type="radio" name="answer" id="answerD" value="D" data-theme="a" />
	         <label for="answerD">You shall not put the <span class='tetragrammaton'>Lord</span> your God to the test.</label>

         </fieldset>
      </div><!-- data-role: content -->

      <div id="BQ_footer" data-role="footer" data-position="fixed" data-id="nav" data-theme="b">
         <div data-role="navbar">
            <ul id="BQ_Game_secondary">
               <li><a>23 seconds ...<br/>Final Answer</a></li>
               <li><a href="#BQ_Pause" data-icon="clock">Pause</a></li>
            </ul>
          </div><!-- data-role: navbar -->
      </div><!-- data-role: footer -->

   </div><!-- data-role: page, id: BQ_Game -->

   <!-- ======================================================================================= -->
